import { type PokemonType, type MoveCategory } from "~/lib/types";

export interface MoveSummary {
  slug: string;
  displayName: string;
  type: PokemonType;
  category: MoveCategory;
  power: number | null;
  accuracy: number | null;
  pp: number;
}

export const COMPETITIVE_MOVES: MoveSummary[] = [
  // ── Physical ──────────────────────────────────────────────────────────────────
  { slug: "earthquake",        displayName: "Earthquake",        type: "ground",   category: "physical", power: 100, accuracy: 100, pp: 10 },
  { slug: "close-combat",      displayName: "Close Combat",      type: "fighting", category: "physical", power: 120, accuracy: 100, pp: 5  },
  { slug: "iron-head",         displayName: "Iron Head",         type: "steel",    category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "play-rough",        displayName: "Play Rough",        type: "fairy",    category: "physical", power: 90,  accuracy: 90,  pp: 10 },
  { slug: "extreme-speed",     displayName: "Extreme Speed",     type: "normal",   category: "physical", power: 80,  accuracy: 100, pp: 5  },
  { slug: "sucker-punch",      displayName: "Sucker Punch",      type: "dark",     category: "physical", power: 70,  accuracy: 100, pp: 5  },
  { slug: "bullet-punch",      displayName: "Bullet Punch",      type: "steel",    category: "physical", power: 40,  accuracy: 100, pp: 30 },
  { slug: "ice-punch",         displayName: "Ice Punch",         type: "ice",      category: "physical", power: 75,  accuracy: 100, pp: 15 },
  { slug: "thunder-punch",     displayName: "Thunder Punch",     type: "electric", category: "physical", power: 75,  accuracy: 100, pp: 15 },
  { slug: "fire-punch",        displayName: "Fire Punch",        type: "fire",     category: "physical", power: 75,  accuracy: 100, pp: 15 },
  { slug: "knock-off",         displayName: "Knock Off",         type: "dark",     category: "physical", power: 65,  accuracy: 100, pp: 20 },
  { slug: "u-turn",            displayName: "U-turn",            type: "bug",      category: "physical", power: 70,  accuracy: 100, pp: 20 },
  { slug: "aqua-jet",          displayName: "Aqua Jet",          type: "water",    category: "physical", power: 40,  accuracy: 100, pp: 20 },
  { slug: "ice-shard",         displayName: "Ice Shard",         type: "ice",      category: "physical", power: 40,  accuracy: 100, pp: 30 },
  { slug: "mach-punch",        displayName: "Mach Punch",        type: "fighting", category: "physical", power: 40,  accuracy: 100, pp: 30 },
  { slug: "wood-hammer",       displayName: "Wood Hammer",       type: "grass",    category: "physical", power: 120, accuracy: 100, pp: 15 },
  { slug: "outrage",           displayName: "Outrage",           type: "dragon",   category: "physical", power: 120, accuracy: 100, pp: 10 },
  { slug: "dragon-claw",       displayName: "Dragon Claw",       type: "dragon",   category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "waterfall",         displayName: "Waterfall",         type: "water",    category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "facade",            displayName: "Facade",            type: "normal",   category: "physical", power: 70,  accuracy: 100, pp: 20 },
  { slug: "body-press",        displayName: "Body Press",        type: "fighting", category: "physical", power: 80,  accuracy: 100, pp: 10 },
  { slug: "drain-punch",       displayName: "Drain Punch",       type: "fighting", category: "physical", power: 75,  accuracy: 100, pp: 10 },
  { slug: "poison-jab",        displayName: "Poison Jab",        type: "poison",   category: "physical", power: 80,  accuracy: 100, pp: 20 },
  { slug: "stone-edge",        displayName: "Stone Edge",        type: "rock",     category: "physical", power: 100, accuracy: 80,  pp: 5  },
  { slug: "rock-slide",        displayName: "Rock Slide",        type: "rock",     category: "physical", power: 75,  accuracy: 90,  pp: 10 },
  { slug: "drill-run",         displayName: "Drill Run",         type: "ground",   category: "physical", power: 80,  accuracy: 95,  pp: 10 },
  { slug: "high-horsepower",   displayName: "High Horsepower",   type: "ground",   category: "physical", power: 95,  accuracy: 95,  pp: 10 },
  { slug: "stomping-tantrum",  displayName: "Stomping Tantrum",  type: "ground",   category: "physical", power: 75,  accuracy: 100, pp: 10 },
  { slug: "lunge",             displayName: "Lunge",             type: "bug",      category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "first-impression",  displayName: "First Impression",  type: "bug",      category: "physical", power: 90,  accuracy: 100, pp: 10 },
  { slug: "leaf-blade",        displayName: "Leaf Blade",        type: "grass",    category: "physical", power: 90,  accuracy: 100, pp: 15 },
  { slug: "sacred-sword",      displayName: "Sacred Sword",      type: "fighting", category: "physical", power: 90,  accuracy: 100, pp: 15 },
  { slug: "smart-strike",      displayName: "Smart Strike",      type: "steel",    category: "physical", power: 70,  accuracy: null, pp: 10 },
  { slug: "brave-bird",        displayName: "Brave Bird",        type: "flying",   category: "physical", power: 120, accuracy: 100, pp: 15 },
  { slug: "gunk-shot",         displayName: "Gunk Shot",         type: "poison",   category: "physical", power: 120, accuracy: 80,  pp: 5  },
  { slug: "zen-headbutt",      displayName: "Zen Headbutt",      type: "psychic",  category: "physical", power: 80,  accuracy: 90,  pp: 15 },
  { slug: "crunch",            displayName: "Crunch",            type: "dark",     category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "shadow-claw",       displayName: "Shadow Claw",       type: "ghost",    category: "physical", power: 70,  accuracy: 100, pp: 15 },
  { slug: "phantom-force",     displayName: "Phantom Force",     type: "ghost",    category: "physical", power: 90,  accuracy: 100, pp: 10 },
  { slug: "flare-blitz",       displayName: "Flare Blitz",       type: "fire",     category: "physical", power: 120, accuracy: 100, pp: 15 },
  { slug: "wild-charge",       displayName: "Wild Charge",       type: "electric", category: "physical", power: 90,  accuracy: 100, pp: 15 },
  { slug: "icicle-crash",      displayName: "Icicle Crash",      type: "ice",      category: "physical", power: 85,  accuracy: 90,  pp: 10 },
  { slug: "seed-bomb",         displayName: "Seed Bomb",         type: "grass",    category: "physical", power: 80,  accuracy: 100, pp: 15 },
  { slug: "power-whip",        displayName: "Power Whip",        type: "grass",    category: "physical", power: 120, accuracy: 85,  pp: 10 },
  { slug: "high-jump-kick",    displayName: "High Jump Kick",    type: "fighting", category: "physical", power: 130, accuracy: 90,  pp: 10 },
  { slug: "liquidation",       displayName: "Liquidation",       type: "water",    category: "physical", power: 85,  accuracy: 100, pp: 10 },
  { slug: "foul-play",         displayName: "Foul Play",         type: "dark",     category: "physical", power: 95,  accuracy: 100, pp: 15 },
  { slug: "spirit-break",      displayName: "Spirit Break",      type: "fairy",    category: "physical", power: 75,  accuracy: 100, pp: 15 },
  { slug: "thousand-arrows",   displayName: "Thousand Arrows",   type: "ground",   category: "physical", power: 90,  accuracy: 100, pp: 10 },
  { slug: "flip-turn",         displayName: "Flip Turn",         type: "water",    category: "physical", power: 60,  accuracy: 100, pp: 20 },
  { slug: "acrobatics",        displayName: "Acrobatics",        type: "flying",   category: "physical", power: 55,  accuracy: 100, pp: 15 },
  { slug: "rapid-spin",        displayName: "Rapid Spin",        type: "normal",   category: "physical", power: 50,  accuracy: 100, pp: 40 },
  { slug: "precipice-blades",  displayName: "Precipice Blades",  type: "ground",   category: "physical", power: 120, accuracy: 85,  pp: 10 },

  // ── Special ───────────────────────────────────────────────────────────────────
  { slug: "flamethrower",      displayName: "Flamethrower",      type: "fire",     category: "special",  power: 90,  accuracy: 100, pp: 15 },
  { slug: "fire-blast",        displayName: "Fire Blast",        type: "fire",     category: "special",  power: 110, accuracy: 85,  pp: 5  },
  { slug: "overheat",          displayName: "Overheat",          type: "fire",     category: "special",  power: 130, accuracy: 90,  pp: 5  },
  { slug: "eruption",          displayName: "Eruption",          type: "fire",     category: "special",  power: 150, accuracy: 100, pp: 5  },
  { slug: "hydro-pump",        displayName: "Hydro Pump",        type: "water",    category: "special",  power: 110, accuracy: 80,  pp: 5  },
  { slug: "surf",              displayName: "Surf",              type: "water",    category: "special",  power: 90,  accuracy: 100, pp: 15 },
  { slug: "scald",             displayName: "Scald",             type: "water",    category: "special",  power: 80,  accuracy: 100, pp: 15 },
  { slug: "water-spout",       displayName: "Water Spout",       type: "water",    category: "special",  power: 150, accuracy: 100, pp: 5  },
  { slug: "origin-pulse",      displayName: "Origin Pulse",      type: "water",    category: "special",  power: 110, accuracy: 85,  pp: 10 },
  { slug: "thunderbolt",       displayName: "Thunderbolt",       type: "electric", category: "special",  power: 90,  accuracy: 100, pp: 15 },
  { slug: "thunder",           displayName: "Thunder",           type: "electric", category: "special",  power: 110, accuracy: 70,  pp: 10 },
  { slug: "volt-switch",       displayName: "Volt Switch",       type: "electric", category: "special",  power: 70,  accuracy: 100, pp: 20 },
  { slug: "electroweb",        displayName: "Electroweb",        type: "electric", category: "special",  power: 55,  accuracy: 95,  pp: 15 },
  { slug: "ice-beam",          displayName: "Ice Beam",          type: "ice",      category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "blizzard",          displayName: "Blizzard",          type: "ice",      category: "special",  power: 110, accuracy: 70,  pp: 5  },
  { slug: "icy-wind",          displayName: "Icy Wind",          type: "ice",      category: "special",  power: 55,  accuracy: 95,  pp: 15 },
  { slug: "psychic",           displayName: "Psychic",           type: "psychic",  category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "psyshock",          displayName: "Psyshock",          type: "psychic",  category: "special",  power: 80,  accuracy: 100, pp: 10 },
  { slug: "shadow-ball",       displayName: "Shadow Ball",       type: "ghost",    category: "special",  power: 80,  accuracy: 100, pp: 15 },
  { slug: "energy-ball",       displayName: "Energy Ball",       type: "grass",    category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "solar-beam",        displayName: "Solar Beam",        type: "grass",    category: "special",  power: 120, accuracy: 100, pp: 10 },
  { slug: "leaf-storm",        displayName: "Leaf Storm",        type: "grass",    category: "special",  power: 130, accuracy: 90,  pp: 5  },
  { slug: "moonblast",         displayName: "Moonblast",         type: "fairy",    category: "special",  power: 95,  accuracy: 100, pp: 15 },
  { slug: "dazzling-gleam",    displayName: "Dazzling Gleam",    type: "fairy",    category: "special",  power: 80,  accuracy: 100, pp: 10 },
  { slug: "focus-blast",       displayName: "Focus Blast",       type: "fighting", category: "special",  power: 120, accuracy: 70,  pp: 5  },
  { slug: "aura-sphere",       displayName: "Aura Sphere",       type: "fighting", category: "special",  power: 80,  accuracy: null, pp: 20 },
  { slug: "dragon-pulse",      displayName: "Dragon Pulse",      type: "dragon",   category: "special",  power: 85,  accuracy: 100, pp: 10 },
  { slug: "draco-meteor",      displayName: "Draco Meteor",      type: "dragon",   category: "special",  power: 130, accuracy: 90,  pp: 5  },
  { slug: "hurricane",         displayName: "Hurricane",         type: "flying",   category: "special",  power: 110, accuracy: 70,  pp: 10 },
  { slug: "boomburst",         displayName: "Boomburst",         type: "normal",   category: "special",  power: 140, accuracy: 100, pp: 10 },
  { slug: "sludge-bomb",       displayName: "Sludge Bomb",       type: "poison",   category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "sludge-wave",       displayName: "Sludge Wave",       type: "poison",   category: "special",  power: 95,  accuracy: 100, pp: 10 },
  { slug: "earth-power",       displayName: "Earth Power",       type: "ground",   category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "flash-cannon",      displayName: "Flash Cannon",      type: "steel",    category: "special",  power: 80,  accuracy: 100, pp: 10 },
  { slug: "dark-pulse",        displayName: "Dark Pulse",        type: "dark",     category: "special",  power: 80,  accuracy: 100, pp: 15 },
  { slug: "bug-buzz",          displayName: "Bug Buzz",          type: "bug",      category: "special",  power: 90,  accuracy: 100, pp: 10 },
  { slug: "air-slash",         displayName: "Air Slash",         type: "flying",   category: "special",  power: 75,  accuracy: 95,  pp: 15 },
  { slug: "stored-power",      displayName: "Stored Power",      type: "psychic",  category: "special",  power: 20,  accuracy: 100, pp: 10 },
  { slug: "power-gem",         displayName: "Power Gem",         type: "rock",     category: "special",  power: 80,  accuracy: 100, pp: 20 },

  // ── Status ────────────────────────────────────────────────────────────────────
  { slug: "protect",           displayName: "Protect",           type: "normal",   category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "tailwind",          displayName: "Tailwind",          type: "flying",   category: "status",   power: null, accuracy: null, pp: 15 },
  { slug: "trick-room",        displayName: "Trick Room",        type: "psychic",  category: "status",   power: null, accuracy: null, pp: 5  },
  { slug: "follow-me",         displayName: "Follow Me",         type: "normal",   category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "rage-powder",       displayName: "Rage Powder",       type: "bug",      category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "helping-hand",      displayName: "Helping Hand",      type: "normal",   category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "wide-guard",        displayName: "Wide Guard",        type: "rock",     category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "quick-guard",       displayName: "Quick Guard",       type: "fighting", category: "status",   power: null, accuracy: null, pp: 15 },
  { slug: "spore",             displayName: "Spore",             type: "grass",    category: "status",   power: null, accuracy: 100,  pp: 15 },
  { slug: "sleep-powder",      displayName: "Sleep Powder",      type: "grass",    category: "status",   power: null, accuracy: 75,   pp: 15 },
  { slug: "toxic",             displayName: "Toxic",             type: "poison",   category: "status",   power: null, accuracy: 90,   pp: 10 },
  { slug: "thunder-wave",      displayName: "Thunder Wave",      type: "electric", category: "status",   power: null, accuracy: 90,   pp: 20 },
  { slug: "will-o-wisp",       displayName: "Will-O-Wisp",       type: "fire",     category: "status",   power: null, accuracy: 85,   pp: 15 },
  { slug: "swords-dance",      displayName: "Swords Dance",      type: "normal",   category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "calm-mind",         displayName: "Calm Mind",         type: "psychic",  category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "nasty-plot",        displayName: "Nasty Plot",        type: "dark",     category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "dragon-dance",      displayName: "Dragon Dance",      type: "dragon",   category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "light-screen",      displayName: "Light Screen",      type: "psychic",  category: "status",   power: null, accuracy: null, pp: 30 },
  { slug: "reflect",           displayName: "Reflect",           type: "psychic",  category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "aurora-veil",       displayName: "Aurora Veil",       type: "ice",      category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "encore",            displayName: "Encore",            type: "normal",   category: "status",   power: null, accuracy: 100,  pp: 5  },
  { slug: "trick",             displayName: "Trick",             type: "psychic",  category: "status",   power: null, accuracy: 100,  pp: 10 },
  { slug: "substitute",        displayName: "Substitute",        type: "normal",   category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "recover",           displayName: "Recover",           type: "normal",   category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "roost",             displayName: "Roost",             type: "flying",   category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "stealth-rock",      displayName: "Stealth Rock",      type: "rock",     category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "sticky-web",        displayName: "Sticky Web",        type: "bug",      category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "spikes",            displayName: "Spikes",            type: "ground",   category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "defog",             displayName: "Defog",             type: "flying",   category: "status",   power: null, accuracy: null, pp: 15 },
  { slug: "haze",              displayName: "Haze",              type: "ice",      category: "status",   power: null, accuracy: null, pp: 30 },
  { slug: "parting-shot",      displayName: "Parting Shot",      type: "dark",     category: "status",   power: null, accuracy: 100,  pp: 20 },
  { slug: "scary-face",        displayName: "Scary Face",        type: "normal",   category: "status",   power: null, accuracy: 100,  pp: 10 },
  { slug: "leech-seed",        displayName: "Leech Seed",        type: "grass",    category: "status",   power: null, accuracy: 90,   pp: 10 },
  { slug: "teleport",          displayName: "Teleport",          type: "psychic",  category: "status",   power: null, accuracy: null, pp: 20 },
  { slug: "chilly-reception",  displayName: "Chilly Reception",  type: "ice",      category: "status",   power: null, accuracy: null, pp: 10 },
  { slug: "cotton-guard",      displayName: "Cotton Guard",      type: "grass",    category: "status",   power: null, accuracy: null, pp: 10 },
];
